Repository PrestaShop/dashactivity, pull requests merged in 2024-04, with the labels that each got.

#41 Update README.md
  README.md
Labels: waiting for author

#43 Display certain links only if the target module is enabled
  views/templates/hook/dashboard_zone_one.tpl
Labels: QA ✔️

#45 Bump version to 2.1.1
  config.xml
  dashactivity.php
Labels: waiting for QA
